// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dashboard-model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Autogenerated _$AutogeneratedFromJson(Map<String, dynamic> json) =>
    Autogenerated(
      drinks: (json['drinks'] as List<dynamic>?)
          ?.map((e) => Drinks.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$AutogeneratedToJson(Autogenerated instance) =>
    <String, dynamic>{
      'drinks': instance.drinks,
    };
