import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';

import '../model/dashboard-model.dart';
import '../utils/constant/api.dart';

enum Status { authenticated, authenticating, unauthenticated }

class APIServicesProvider extends ChangeNotifier {
  Autogenerated? _dashboardDataModel;
  Autogenerated? get dashboardDataModel => _dashboardDataModel;

  Status _status = Status.unauthenticated;

  Status get status => _status;

  final Dio _dio = Dio();

  Dio? get dio => _dio;

  Future<Autogenerated>? getDashboardDataApi() async {
    _status = Status.authenticating;
    return await dio!.get(Api.dashboardData).then((response) {
      _status = Status.authenticated;
      return response.statusCode == 200
          ? Autogenerated.fromJson(response.data)
          : Autogenerated();
    });
  }
}
